FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow==3.8.1

# Dossiers pour artefacts
RUN mkdir -p /mlflow/artifacts

EXPOSE 5000

CMD ["mlflow","server", \
  "--host","0.0.0.0", \
  "--port","5000", \
  "--backend-store-uri","sqlite:///mlflow.db", \
  "--default-artifact-root","/mlflow/artifacts", \
  "--serve-artifacts", \
  "--allowed-hosts","*", \
  "--cors-allowed-origins","*"]
